name: 'Isabelle-action'
description: 'Isabelle image with prebuilt HOL'
inputs:
  args:
    description: 'Isabelle arguments'
    required: true
runs:
  using: 'docker'
  image: 'docker://makarius/isabelle:Isabelle2023'
  args: ${{ inputs.args }}
  entrypoint: '/home/isabelle/Isabelle/bin/isabelle'
