name: 'Isabelle-action'
description: 'Isabelle image with prebuilt HOL'
inputs:
  args:
    description: 'Isabelle arguments'
    required: true
#  heapCacheDir:
#    description: 'path to save to/load from Isabelle session heap'
#    required: false
runs:
  using: 'docker'
  image: 'makarius/isabelle:Isabelle2023'
#  env:
#    HEAP_CACHE_DIR: ${{ inputs.heapCacheDir }}
  args:
    - ${{ inputs.args }}
