name: 'Isabelle-action'
description: 'Isabelle image with prebuilt HOL'
inputs:
  session:
    description: 'Isabelle session name'
    required: true
  output:
    description: 'Isabelle output path'
    default: out
    
runs:
  using: 'docker'
  image: 'docker://hllm/isabelle-docker'
  args:
    - 'build'
    - '-o'
    - 'document=pdf'
    - '-o'
    - 'document_variants=document:outline=/proof,/ML'
    - '-P'
    - ${{ inputs.output }}
    - '-d'
    - '.'
    - ${{ inputs.session }}
