name: 'Isabelle-action'
description: 'Isabelle image with prebuilt HOL'
inputs:
  args:
    description: 'Isabelle arguments'
    required: true
  heapCacheDir:
    description: 'path to save to/load from Isabelle session heap'
    required: false
runs:
  using: 'docker'
  image: 'docker://braewebb/isabelle-action:v1.10'
  env:
    HEAP_CACHE_DIR: ${{ inputs.heapCacheDir }}
  args:
    - ${{ inputs.args }}
